emissions = (
('(a) Carbon Dioxide (CO2, fossil)','g','1'),
('(a) Methane (CH4)','g','8'),
('(a) Nitrous Oxide (N2O)','g','12'),
('(a) Ammonia (NH3)','g','21'),
('(a) Hydrogen Chloride (HCl)','g','22'),
('(a) Hydrogen Fluoride (HF)','g','24'),
('(a) Hydrogen Sulfide (H2S)','g','25'),
('(a) Nitrogen Oxides (NOx as NO2)','g','26'),
('(a) Sulfur Oxides (SOx as SO2)','g','27'),
('(w) Ammonia (NH4+, NH3, as N)','g','47'),
('(w) BOD5 (Biochemical Oxygen Demand)','g','48'),
('(w) COD (Chemical Oxygen Demand)','g','49'),
('(w) Nitrate (NO3-)','g','50'),
('(r) Coal (in ground)','kg','71'),
('(r) Natural Gas (in ground)','kg','72'),
('(r) Oil (in ground)','kg','73'),
('(r) Uranium (U, ore)','kg','74'),
('(w) Water Used (total)','liters','181'),
('(a) Particulates (unspecified)','g','194'),
('(a) Aldehyde (unspecified)','g','210'),
('(a) Benzene (C6H6)','g','218'),
('(a) Carbon Monoxide (CO)','g','237'),
('(a) Formaldehyde (CH2O)','g','266'),
('(a) Hydrocarbons (except methane)','g','272'),
('(a) Hydrocarbons (unspecified)','g','273'),
('(a) Toluene (C6H5CH3)','g','310'),
('(a) Xylene (C6H4(CH3)2)','g','317'),
('(a) Cadmium (Cd)','g','340'),
('(a) Fluorides (F-)','g','363'),
('(a) Lead (Pb)','g','366'),
('(a) Mercury (Hg)','g','370'),
('(w) Chromium (Cr III, Cr VI)','g','413'),
('(w) Hydrocarbons (unspecified)','g','436'),
('(w) Phenol (C6H5OH)','g','458'),
('(w) Zinc (Zn++)','g','477'),
('(e) Total Primary Energy','MJ','800'),
('(e) Feedstock Energy','MJ','801'),
('(e) Fuel Energy','MJ','802'),
('(e) Non Renewable Energy','MJ','803'),
('(e) Renewable Energy','MJ','804'),
)

from carbon.models import EmissionType

for (name, unit, id) in emissions:
	EmissionType.objects.create(name=name, unit=unit, id=id)
